package Tool.Forensics_Log_Analyzer;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
*
* @author g_chawla
*/
public class DDOS_Display extends javax.swing.JFrame {

   /**
    * Creates new form DDOS_Display
    */
   public DDOS_Display() {
       initComponents();
 //Flag    
       String FILENAME = "output/part-r-00000";
       String FILENAME2 = "output2/part-r-00000";
       BufferedReader br = null;
   	FileReader fr = null;
   	BufferedReader br2 = null;
   	FileReader fr2 = null;
   	int[] array = new int[3];
   	int[] array2 = new int[3];
   	try 
   	{
   		fr = new FileReader(FILENAME);
   		br = new BufferedReader(fr);
   		fr2 = new FileReader(FILENAME2);
   		br2 = new BufferedReader(fr2);
   		String sCurrentLine;
   		String sCurrentLine2;		
   		br = new BufferedReader(new FileReader(FILENAME));
   		int j=0;
   		while ((sCurrentLine = br.readLine()) != null) 
   		{
   		String delims = "[	]+";
   		String[] tokens = sCurrentLine.split(delims);
   		for (int i = 0; i < tokens.length; i++)
   			{			
   			tokens[i].toString();
   			i++;
   			array[j]=Integer.parseInt(tokens[i].toString());
   			j++;
   			}
   		}
   		br2 = new BufferedReader(new FileReader(FILENAME2));
   		j=0;
   		while ((sCurrentLine2 = br2.readLine()) != null) 
   		{
   		String delims2 = "[	]+";
   		String[] tokens2 = sCurrentLine2.split(delims2);		
   		for (int i = 0; i < tokens2.length; i++)
   			{			
   			tokens2[i].toString();
   			i++;
   			array2[j]=Integer.parseInt(tokens2[i].toString());
   			j++;
   			}
   		}
   		if(array2[0]>(2*array[0]))
   		{
   			data.append("DDOS DETECTED \n");
   			data.append("Denial request flooding round at 01 hrs at rate of "+array2[0]+" per hour \n");
   			data.append("Regular denail request rate is "+array[0]+"\n");
   			data.append("Generate futher invesigation report to know more \n");
   			
   		}
   		if(array2[1]>(2*array[1]))
   		{
   			data.append("DDOS DETECTED \n");
   			data.append("Denial request flooding round at 02 hrs at rate of "+array2[1]+" per hour \n");
   			data.append("Regular denail request rate is "+array[1]+"\n");
   			data.append("Generate futher invesigation report to know more \n");
   		}
   		
   		
   	}
   	 catch (IOException e) {

   		e.printStackTrace();

   	} finally {

   		try {

   			if (br != null)
   				br.close();
   			if (fr != null)
   				fr.close();
   		} catch (IOException ex) {
   			ex.printStackTrace();
   		}
   	}
   //Flag
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jLabel1 = new javax.swing.JLabel();
       jScrollPane1 = new javax.swing.JScrollPane();
       data = new javax.swing.JTextArea();
       jButton1 = new javax.swing.JButton();
       jButton2 = new javax.swing.JButton();
       jButton3 = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
       jLabel1.setText("DDOS REPORT");

       data.setColumns(20);
       data.setRows(5);
       jScrollPane1.setViewportView(data);

       jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
       jButton1.setText("MAIN MENU");
       jButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1ActionPerformed(evt);
           }
       });

       jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
       jButton2.setText("EXIT");
       jButton2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton2ActionPerformed(evt);
           }
       });

       jButton3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
       jButton3.setText("INVESTIGATE");
       jButton3.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton3ActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGap(240, 240, 240)
                       .addComponent(jLabel1))
                   .addGroup(layout.createSequentialGroup()
                       .addGap(94, 94, 94)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addGroup(layout.createSequentialGroup()
                               .addComponent(jButton1)
                               .addGap(63, 63, 63)
                               .addComponent(jButton3)
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                               .addComponent(jButton2))
                           .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))))
               .addContainerGap(109, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(69, 69, 69)
               .addComponent(jLabel1)
               .addGap(26, 26, 26)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jButton1)
                   .addComponent(jButton2)
                   .addComponent(jButton3))
               .addGap(40, 40, 40))
       );

       pack();
   }// </editor-fold>                        

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // Main menu
		Analysisorder any = new Analysisorder();
		any.setVisible(true);
		dispose();
		String[] args = new String[3];
		args[0] = "output";
		DeleteDir.main(args);
		String[] args2 = new String[3];
		args2[0] = "output2";
		DeleteDir.main(args2);
   }                                        

   private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // Investigate
	   try {
		DDOS_Investigate.main();
	} catch (Exception e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}	dispose();
   }                                        

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       //Exit
		dispose();
		String[] args = new String[3];
		args[0] = "output";
		DeleteDir.main(args);
		String[] args2 = new String[3];
		args2[0] = "output2";
		DeleteDir.main(args2);
   }                                        

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(DDOS_Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(DDOS_Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(DDOS_Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(DDOS_Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new DDOS_Display().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JTextArea data;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JScrollPane jScrollPane1;
   // End of variables declaration                   
}